#!/usr/bin/env python3
"""Generate one Jekyll page per talk from the TOML records in `_data/talks/`.

The TOML files are the source of truth; the markdown pages under `_talks/` are
generated and should never be edited by hand (GitHub Pages builds Jekyll in
safe mode, so the pages have to be generated ahead of time and committed).

Usage:
    python3 scripts/generate_talks.py            # (re)generate _talks/*.md
    python3 scripts/generate_talks.py --check    # fail if pages are out of date
"""

from __future__ import annotations

import argparse
import datetime as dt
import glob
import json
import os
import sys
import tomllib
from zoneinfo import ZoneInfo

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(ROOT, "_data", "talks")
OUT_DIR = os.path.join(ROOT, "_talks")
TZ = ZoneInfo("America/Denver")
BANNER = "<!-- Generated by scripts/generate_talks.py from _data/talks/%s -- do not edit. -->"

SPEAKER_FIELDS = ("name", "affiliation", "role", "website", "photo", "email", "bio")
TALK_FIELDS = (
    "series",
    "location",
    "room",
    "zoom",
    "slides",
    "recording",
    "paper",
    "canceled",
    "tags",
)


class TalkError(Exception):
    pass


def yaml_scalar(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return json.dumps(str(value), ensure_ascii=False)  # JSON strings are valid YAML


def yaml_block(data: dict, indent: int = 0) -> list[str]:
    lines = []
    pad = " " * indent
    for key, value in data.items():
        if value in ("", None, [], {}):
            continue
        if isinstance(value, list):
            if all(isinstance(item, dict) for item in value):
                lines.append(f"{pad}{key}:")
                for item in value:
                    inner = yaml_block(item, indent + 4)
                    if not inner:
                        continue
                    lines.append(f"{pad}  - " + inner[0].strip())
                    lines.extend(inner[1:])
            else:
                lines.append(f"{pad}{key}: [" + ", ".join(yaml_scalar(v) for v in value) + "]")
        else:
            lines.append(f"{pad}{key}: {yaml_scalar(value)}")
    return lines


def parse_time(value, field: str, source: str) -> dt.time | None:
    if value in (None, ""):
        return None
    if isinstance(value, dt.time):
        return value
    for fmt in ("%H:%M", "%H:%M:%S", "%I:%M %p", "%I%p"):
        try:
            return dt.datetime.strptime(str(value).strip().upper(), fmt.upper()).time()
        except ValueError:
            continue
    raise TalkError(f"{source}: could not parse {field} {value!r} (use e.g. \"13:30\")")


def load_talk(path: str) -> dict:
    source = os.path.basename(path)
    with open(path, "rb") as handle:
        try:
            raw = tomllib.load(handle)
        except tomllib.TOMLDecodeError as error:
            raise TalkError(f"{source}: invalid TOML ({error})") from error

    talk = raw.get("talk")
    if not isinstance(talk, dict):
        raise TalkError(f"{source}: missing a [talk] table")
    if not talk.get("title"):
        raise TalkError(f"{source}: [talk] needs a title")

    date = talk.get("date")
    if isinstance(date, dt.datetime):
        date = date.date()
    if not isinstance(date, dt.date):
        raise TalkError(f"{source}: [talk] needs a date (e.g. date = 2026-09-04)")

    speakers = raw.get("speakers") or []
    if not isinstance(speakers, list) or not speakers:
        raise TalkError(f"{source}: needs at least one [[speakers]] entry")
    for speaker in speakers:
        if not speaker.get("name"):
            raise TalkError(f"{source}: every [[speakers]] entry needs a name")

    start = parse_time(talk.get("start_time"), "start_time", source)
    end = parse_time(talk.get("end_time"), "end_time", source)
    starts_at = dt.datetime.combine(date, start or dt.time(13, 30), tzinfo=TZ)

    slug = talk.get("slug") or os.path.splitext(source)[0]
    front = {
        "layout": "talk",
        "title": talk["title"],
        "date": starts_at.strftime("%Y-%m-%d %H:%M:%S %z"),
        "permalink": f"/talks/{slug}/",
        "slug": slug,
    }
    if start:
        front["start_time"] = starts_at.strftime("%-I:%M %p")
    if end:
        front["end_time"] = dt.datetime.combine(date, end, tzinfo=TZ).strftime("%-I:%M %p")
    for field in TALK_FIELDS:
        if field in talk:
            front[field] = talk[field]
    front["speakers"] = [
        {field: speaker[field] for field in SPEAKER_FIELDS if speaker.get(field)}
        for speaker in speakers
    ]
    front["speaker_names"] = ", ".join(speaker["name"] for speaker in speakers)
    front["source_file"] = f"_data/talks/{source}"
    front["generated"] = True

    body = str(talk.get("abstract", "")).strip()
    return {"source": source, "slug": slug, "front": front, "body": body}


def render(talk: dict) -> str:
    lines = ["---"]
    lines += yaml_block(talk["front"])
    lines += ["---", "", BANNER % talk["source"], ""]
    if talk["body"]:
        # abstracts are prose, so protect any accidental Liquid from the build
        if "{{" in talk["body"] or "{%" in talk["body"]:
            lines += ["{% raw %}", talk["body"], "{% endraw %}", ""]
        else:
            lines += [talk["body"], ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write anything; exit non-zero if pages are out of date",
    )
    args = parser.parse_args()

    os.makedirs(OUT_DIR, exist_ok=True)
    sources = sorted(
        path
        for path in glob.glob(os.path.join(DATA_DIR, "*.toml"))
        if not os.path.basename(path).startswith("_")
    )

    pages, errors, seen = {}, [], {}
    for path in sources:
        try:
            talk = load_talk(path)
        except TalkError as error:
            errors.append(str(error))
            continue
        if talk["slug"] in seen:
            errors.append(
                f'{talk["source"]}: duplicate talk slug "{talk["slug"]}" '
                f'(also used by {seen[talk["slug"]]})'
            )
            continue
        seen[talk["slug"]] = talk["source"]
        pages[os.path.join(OUT_DIR, f'{os.path.splitext(talk["source"])[0]}.md')] = render(talk)

    if errors:
        for error in errors:
            print(f"error: {error}", file=sys.stderr)
        return 1

    existing = set(glob.glob(os.path.join(OUT_DIR, "*.md")))
    stale = sorted(existing - set(pages))
    changed = sorted(
        path
        for path, content in pages.items()
        if not os.path.exists(path) or open(path, encoding="utf-8").read() != content
    )

    if args.check:
        if changed or stale:
            for path in changed:
                print(f"out of date: {os.path.relpath(path, ROOT)}", file=sys.stderr)
            for path in stale:
                print(f"orphaned:    {os.path.relpath(path, ROOT)}", file=sys.stderr)
            print(
                "\nRun `make talks` (or python3 scripts/generate_talks.py) and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"{len(pages)} talk page(s) up to date")
        return 0

    for path in changed:
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(pages[path])
    for path in stale:
        os.remove(path)

    print(
        f"{len(pages)} talk page(s) in {os.path.relpath(OUT_DIR, ROOT)}/ "
        f"({len(changed)} written, {len(stale)} removed)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
