#!/usr/bin/env python3
"""Generate a page per talk, and the calendar feed, from `_data/talks/*.toml`.

The TOML files are the source of truth. Everything this writes is generated and
should never be edited by hand:

    _talks/*.md   one Jekyll page per talk
    talks.ics     an iCalendar feed of every talk, served at /talks.ics

(GitHub Pages builds Jekyll in safe mode, so custom plugins are unavailable and
both have to be generated ahead of time and committed.)

Usage:
    python3 scripts/generate_talks.py            # (re)generate everything
    python3 scripts/generate_talks.py --check    # fail if the output is stale
"""

from __future__ import annotations

import argparse
import datetime as dt
import glob
import json
import os
import re
import sys
import tomllib
from zoneinfo import ZoneInfo

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(ROOT, "_data", "talks")
OUT_DIR = os.path.join(ROOT, "_talks")
ICS_PATH = os.path.join(ROOT, "talks.ics")
TZ = ZoneInfo("America/Denver")
CALENDAR_NAME = "Utah Data Science & AI Lecture Series"
CALENDAR_DESC = (
    "Talks in the Data Science & AI Lecture Series at the Utah Center for Data "
    "Science. Generated from the talk records at datascience.utah.edu/talks/."
)
BANNER = "<!-- Generated by scripts/generate_talks.py from _data/talks/%s -- do not edit. -->"

SPEAKER_FIELDS = ("name", "affiliation", "role", "website", "photo", "email", "bio")
TALK_FIELDS = (
    "series",
    "location",
    "room",
    "zoom",
    "slides",
    "recording",
    "paper",
    "canceled",
    "tags",
)


class TalkError(Exception):
    pass


def yaml_scalar(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return json.dumps(str(value), ensure_ascii=False)  # JSON strings are valid YAML


def yaml_block(data: dict, indent: int = 0) -> list[str]:
    lines = []
    pad = " " * indent
    for key, value in data.items():
        if value in ("", None, [], {}):
            continue
        if isinstance(value, list):
            if all(isinstance(item, dict) for item in value):
                lines.append(f"{pad}{key}:")
                for item in value:
                    inner = yaml_block(item, indent + 4)
                    if not inner:
                        continue
                    lines.append(f"{pad}  - " + inner[0].strip())
                    lines.extend(inner[1:])
            else:
                lines.append(f"{pad}{key}: [" + ", ".join(yaml_scalar(v) for v in value) + "]")
        else:
            lines.append(f"{pad}{key}: {yaml_scalar(value)}")
    return lines


def parse_time(value, field: str, source: str) -> dt.time | None:
    if value in (None, ""):
        return None
    if isinstance(value, dt.time):
        return value
    for fmt in ("%H:%M", "%H:%M:%S", "%I:%M %p", "%I%p"):
        try:
            return dt.datetime.strptime(str(value).strip().upper(), fmt.upper()).time()
        except ValueError:
            continue
    raise TalkError(f"{source}: could not parse {field} {value!r} (use e.g. \"13:30\")")


def load_talk(path: str) -> dict:
    source = os.path.basename(path)
    with open(path, "rb") as handle:
        try:
            raw = tomllib.load(handle)
        except tomllib.TOMLDecodeError as error:
            raise TalkError(f"{source}: invalid TOML ({error})") from error

    talk = raw.get("talk")
    if not isinstance(talk, dict):
        raise TalkError(f"{source}: missing a [talk] table")
    if not talk.get("title"):
        raise TalkError(f"{source}: [talk] needs a title")

    date = talk.get("date")
    if isinstance(date, dt.datetime):
        date = date.date()
    if not isinstance(date, dt.date):
        raise TalkError(f"{source}: [talk] needs a date (e.g. date = 2026-09-04)")

    speakers = raw.get("speakers") or []
    if not isinstance(speakers, list) or not speakers:
        raise TalkError(f"{source}: needs at least one [[speakers]] entry")
    for speaker in speakers:
        if not speaker.get("name"):
            raise TalkError(f"{source}: every [[speakers]] entry needs a name")

    start = parse_time(talk.get("start_time"), "start_time", source)
    end = parse_time(talk.get("end_time"), "end_time", source)
    starts_at = dt.datetime.combine(date, start or dt.time(13, 30), tzinfo=TZ)

    slug = talk.get("slug") or os.path.splitext(source)[0]
    # a page headed "TBA" helps nobody; name it after whoever gave the talk
    title = str(talk["title"]).strip()
    if re.fullmatch(r"(?i)tba|tbd", title):
        title = "Talk by " + ", ".join(speaker["name"] for speaker in speakers)
    front = {
        "layout": "talk",
        "title": title,
        "date": starts_at.strftime("%Y-%m-%d %H:%M:%S %z"),
        "permalink": f"/talks/{slug}/",
        "slug": slug,
    }
    if start:
        front["start_time"] = starts_at.strftime("%-I:%M %p")
    if end:
        front["end_time"] = dt.datetime.combine(date, end, tzinfo=TZ).strftime("%-I:%M %p")
    for field in TALK_FIELDS:
        if field in talk:
            front[field] = talk[field]
    front["speakers"] = [
        {field: speaker[field] for field in SPEAKER_FIELDS if speaker.get(field)}
        for speaker in speakers
    ]
    front["speaker_names"] = ", ".join(speaker["name"] for speaker in speakers)
    front["source_file"] = f"_data/talks/{source}"
    front["generated"] = True

    body = str(talk.get("abstract", "")).strip()
    return {
        "source": source,
        "slug": slug,
        "front": front,
        "body": body,
        "starts_at": starts_at,
        "ends_at": dt.datetime.combine(date, end, tzinfo=TZ) if end else None,
        "speakers": speakers,
    }


def render(talk: dict) -> str:
    lines = ["---"]
    lines += yaml_block(talk["front"])
    lines += ["---", "", BANNER % talk["source"], ""]
    if talk["body"]:
        # abstracts are prose, so protect any accidental Liquid from the build
        if "{{" in talk["body"] or "{%" in talk["body"]:
            lines += ["{% raw %}", talk["body"], "{% endraw %}", ""]
        else:
            lines += [talk["body"], ""]
    return "\n".join(lines)



# --------------------------------------------------------------------------- #
# iCalendar feed
# --------------------------------------------------------------------------- #
def site_url() -> str:
    """The site's own address, taken from CNAME so the two cannot disagree."""
    cname = os.path.join(ROOT, "CNAME")
    if os.path.exists(cname):
        host = open(cname, encoding="utf-8").read().strip()
        if host:
            return f"https://{host}"
    return "https://utah-datascience.github.io"


def ics_escape(value: str) -> str:
    return (
        str(value)
        .replace("\\", "\\\\")
        .replace(";", "\\;")
        .replace(",", "\\,")
        .replace("\r\n", "\\n")
        .replace("\n", "\\n")
    )


def ics_fold(line: str) -> list[str]:
    """RFC 5545 says content lines are folded at 75 octets, continued with a space."""
    raw = line.encode("utf-8")
    if len(raw) <= 75:
        return [line]
    chunks, start = [], 0
    limit = 75
    while start < len(raw):
        end = min(start + limit, len(raw))
        while end < len(raw) and (raw[end] & 0xC0) == 0x80:  # never split a character
            end -= 1
        chunks.append(raw[start:end].decode("utf-8"))
        start = end
        limit = 74  # continuation lines carry a leading space
    return [chunks[0]] + [" " + chunk for chunk in chunks[1:]]


def ics_stamp(moment: dt.datetime) -> str:
    return moment.astimezone(dt.timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def ics_local(moment: dt.datetime) -> str:
    return moment.strftime("%Y%m%dT%H%M%S")


def event_description(talk: dict) -> str:
    front = talk["front"]
    parts = []
    who = []
    for speaker in talk["speakers"]:
        name = speaker["name"]
        if speaker.get("affiliation"):
            name += f' ({speaker["affiliation"]})'
        who.append(name)
    if who:
        parts.append(", ".join(who))
    if talk["body"]:
        parts.append(talk["body"])
    for label, field in (("Slides", "slides"), ("Recording", "recording")):
        if front.get(field):
            parts.append(f'{label}: {front[field]}')
    parts.append(f'{site_url()}{front["permalink"]}')
    return "\n\n".join(parts)


def build_ics(talks: list[dict]) -> str:
    lines = [
        "BEGIN:VCALENDAR",
        "VERSION:2.0",
        "PRODID:-//Utah Center for Data Science//Talks//EN",
        "CALSCALE:GREGORIAN",
        "METHOD:PUBLISH",
        f"X-WR-CALNAME:{ics_escape(CALENDAR_NAME)}",
        f"X-WR-CALDESC:{ics_escape(CALENDAR_DESC)}",
        "X-WR-TIMEZONE:America/Denver",
        # a hint to subscribers about how often to re-read the feed; Apple and
        # Outlook honour it, Google refreshes on its own schedule regardless
        "REFRESH-INTERVAL;VALUE=DURATION:PT1H",
        "X-PUBLISHED-TTL:PT1H",
        # Mountain Time, so the feed is correct for subscribers in any timezone
        "BEGIN:VTIMEZONE",
        "TZID:America/Denver",
        "BEGIN:DAYLIGHT",
        "TZOFFSETFROM:-0700",
        "TZOFFSETTO:-0600",
        "TZNAME:MDT",
        "DTSTART:19700308T020000",
        "RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU",
        "END:DAYLIGHT",
        "BEGIN:STANDARD",
        "TZOFFSETFROM:-0600",
        "TZOFFSETTO:-0700",
        "TZNAME:MST",
        "DTSTART:19701101T020000",
        "RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU",
        "END:STANDARD",
        "END:VTIMEZONE",
    ]

    for talk in sorted(talks, key=lambda item: item["starts_at"]):
        front = talk["front"]
        starts = talk["starts_at"]
        ends = talk["ends_at"] or (starts + dt.timedelta(hours=1))
        summary = front["title"]
        if front.get("speaker_names"):
            summary += f' - {front["speaker_names"]}'
        lines += [
            "BEGIN:VEVENT",
            f'UID:{talk["slug"]}@{site_url().split("://")[1]}',
            # deliberately derived from the event, not from "now", so that
            # regenerating an unchanged record produces an unchanged file
            f"DTSTAMP:{ics_stamp(starts)}",
            f"DTSTART;TZID=America/Denver:{ics_local(starts)}",
            f"DTEND;TZID=America/Denver:{ics_local(ends)}",
            f"SUMMARY:{ics_escape(summary)}",
            f"DESCRIPTION:{ics_escape(event_description(talk))}",
            f'URL:{site_url()}{front["permalink"]}',
            "SEQUENCE:0",
            f'STATUS:{"CANCELLED" if front.get("canceled") else "CONFIRMED"}',
            "TRANSP:OPAQUE",
        ]
        location = front.get("location") or ""
        if front.get("zoom"):
            location = f'{location} | {front["zoom"]}' if location else front["zoom"]
        if location:
            lines.append(f"LOCATION:{ics_escape(location)}")
        if front.get("tags"):
            lines.append(f'CATEGORIES:{",".join(ics_escape(tag) for tag in front["tags"])}')
        lines.append("END:VEVENT")

    lines.append("END:VCALENDAR")

    folded = []
    for line in lines:
        folded.extend(ics_fold(line))
    return "\r\n".join(folded) + "\r\n"


def read_text(path: str) -> str:
    with open(path, encoding="utf-8", newline="") as handle:
        return handle.read()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write anything; exit non-zero if pages are out of date",
    )
    args = parser.parse_args()

    os.makedirs(OUT_DIR, exist_ok=True)
    sources = sorted(
        path
        for path in glob.glob(os.path.join(DATA_DIR, "*.toml"))
        if not os.path.basename(path).startswith("_")
    )

    pages, errors, seen, records = {}, [], {}, []
    for path in sources:
        try:
            talk = load_talk(path)
        except TalkError as error:
            errors.append(str(error))
            continue
        if talk["slug"] in seen:
            errors.append(
                f'{talk["source"]}: duplicate talk slug "{talk["slug"]}" '
                f'(also used by {seen[talk["slug"]]})'
            )
            continue
        seen[talk["slug"]] = talk["source"]
        records.append(talk)
        pages[os.path.join(OUT_DIR, f'{os.path.splitext(talk["source"])[0]}.md')] = render(talk)

    if errors:
        for error in errors:
            print(f"error: {error}", file=sys.stderr)
        return 1

    pages[ICS_PATH] = build_ics(records)

    existing = set(glob.glob(os.path.join(OUT_DIR, "*.md")))
    stale = sorted(existing - set(pages))
    changed = sorted(
        path
        for path, content in pages.items()
        if not os.path.exists(path) or read_text(path) != content
    )

    if args.check:
        if changed or stale:
            for path in changed:
                print(f"out of date: {os.path.relpath(path, ROOT)}", file=sys.stderr)
            for path in stale:
                print(f"orphaned:    {os.path.relpath(path, ROOT)}", file=sys.stderr)
            print(
                "\nRun `make talks` (or python3 scripts/generate_talks.py) and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"{len(records)} talk page(s) and talks.ics up to date")
        return 0

    for path in changed:
        # newline="" keeps the CRLF line endings the iCalendar feed needs
        with open(path, "w", encoding="utf-8", newline="") as handle:
            handle.write(pages[path])
    for path in stale:
        os.remove(path)

    print(
        f"{len(records)} talk page(s) in {os.path.relpath(OUT_DIR, ROOT)}/ plus "
        f"talks.ics ({len(changed)} written, {len(stale)} removed)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
